# Create Pandas Series

In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
a = pd.Series([1,2,3,4,5])

In [4]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(a)

pandas.core.series.Series

In [6]:
a[2]

3

In [7]:
a = pd.Series(['a','b','c'])

In [8]:
a

0    a
1    b
2    c
dtype: object

In [9]:
a = pd.date_range(start = '01-01-2019', end = '24-10-2019')

In [10]:
a

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-10-15', '2019-10-16', '2019-10-17', '2019-10-18',
               '2019-10-19', '2019-10-20', '2019-10-21', '2019-10-22',
               '2019-10-23', '2019-10-24'],
              dtype='datetime64[ns]', length=297, freq='D')

In [11]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

# Pandas dataframe

In [12]:
name = ['Shakti', 'Hemanka', 'Rajeshwari', 'Akshaya', 'Fenil']

In [13]:
domain = ['NLP', 'Reinforcement Learning', 'Computer Vision', 'Analytrics', 'Automation']

In [14]:
experience = [2, 3, 4, 5, 6]

In [15]:
dct = {'Name': name, 'Domain': domain, 'Experience': experience}

In [16]:
data = pd.DataFrame(dct)

In [17]:
data

Name                  Domain  Experience
0      Shakti                     NLP           2
1     Hemanka  Reinforcement Learning           3
2  Rajeshwari         Computer Vision           4
3     Akshaya              Analytrics           5
4       Fenil              Automation           6

In [18]:
zipped = list(zip(name, domain, experience))

In [19]:
zipped

[('Shakti', 'NLP', 2),
 ('Hemanka', 'Reinforcement Learning', 3),
 ('Rajeshwari', 'Computer Vision', 4),
 ('Akshaya', 'Analytrics', 5),
 ('Fenil', 'Automation', 6)]

In [20]:
data = {'Name':name,
       'Domain':domain,
       'Experience':experience}

In [21]:
df = pd.DataFrame(data)

In [22]:
df

Name                  Domain  Experience
0      Shakti                     NLP           2
1     Hemanka  Reinforcement Learning           3
2  Rajeshwari         Computer Vision           4
3     Akshaya              Analytrics           5
4       Fenil              Automation           6

In [23]:
import numpy as np

In [24]:
np.random.randint(low=10, high=100, size=10)

array([53, 37, 34, 84, 44, 79, 78, 24, 35, 23])

In [25]:
np.random.choice([1, 2, 3, 4, 5, 6], 5)

array([4, 6, 2, 5, 6])

In [112]:
temp = np.random.randint(low = 20, high =100, size = [20,])
name = np.random.choice(['Shakti', 'Hemanka', 'Rajeshwari', 'Akshaya', 'Fenil'], 20)
random = np.random.choice([10,11,13,12,14], 20)

In [113]:
temp

array([93, 57, 61, 64, 80, 64, 34, 37, 64, 47, 56, 82, 67, 36, 47, 65, 41,
       79, 94, 29])

In [114]:
name

array(['Rajeshwari', 'Fenil', 'Akshaya', 'Akshaya', 'Rajeshwari',
       'Akshaya', 'Hemanka', 'Rajeshwari', 'Rajeshwari', 'Shakti',
       'Shakti', 'Akshaya', 'Shakti', 'Hemanka', 'Hemanka', 'Akshaya',
       'Shakti', 'Akshaya', 'Shakti', 'Hemanka'], dtype='<U10')

In [115]:
random

array([10, 13, 10, 10, 11, 10, 12, 13, 11, 11, 11, 13, 14, 11, 11, 11, 11,
       10, 10, 14])

In [116]:
a = list(zip(temp, name, random))

In [117]:
a

[(93, 'Rajeshwari', 10),
 (57, 'Fenil', 13),
 (61, 'Akshaya', 10),
 (64, 'Akshaya', 10),
 (80, 'Rajeshwari', 11),
 (64, 'Akshaya', 10),
 (34, 'Hemanka', 12),
 (37, 'Rajeshwari', 13),
 (64, 'Rajeshwari', 11),
 (47, 'Shakti', 11),
 (56, 'Shakti', 11),
 (82, 'Akshaya', 13),
 (67, 'Shakti', 14),
 (36, 'Hemanka', 11),
 (47, 'Hemanka', 11),
 (65, 'Akshaya', 11),
 (41, 'Shakti', 11),
 (79, 'Akshaya', 10),
 (94, 'Shakti', 10),
 (29, 'Hemanka', 14)]

In [118]:
df = pd.DataFrame(data = a, columns=['temp','name','random'])

In [119]:
df

temp        name  random
0     93  Rajeshwari      10
1     57       Fenil      13
2     61     Akshaya      10
3     64     Akshaya      10
4     80  Rajeshwari      11
5     64     Akshaya      10
6     34     Hemanka      12
7     37  Rajeshwari      13
8     64  Rajeshwari      11
9     47      Shakti      11
10    56      Shakti      11
11    82     Akshaya      13
12    67      Shakti      14
13    36     Hemanka      11
14    47     Hemanka      11
15    65     Akshaya      11
16    41      Shakti      11
17    79     Akshaya      10
18    94      Shakti      10
19    29     Hemanka      14

In [124]:
df.head()

temp        name  random
0    93  Rajeshwari      10
1    57       Fenil      13
2    61     Akshaya      10
3    64     Akshaya      10
4    80  Rajeshwari      11

In [128]:
df.tail()

temp     name  random
15    65  Akshaya      11
16    41   Shakti      11
17    79  Akshaya      10
18    94   Shakti      10
19    29  Hemanka      14

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int64
name      20 non-null object
random    20 non-null int64
dtypes: int64(2), object(1)
memory usage: 560.0+ bytes


In [38]:
df.shape

(20, 3)

In [39]:
df.describe()

temp     random
count  20.000000  20.000000
mean   54.400000  11.650000
std    23.609543   1.424411
min    20.000000  10.000000
25%    36.250000  10.750000
50%    57.000000  11.000000
75%    69.000000  13.000000
max    97.000000  14.000000

In [129]:
df['name'].head()

0    Rajeshwari
1         Fenil
2       Akshaya
3       Akshaya
4    Rajeshwari
Name: name, dtype: object

In [41]:
temp = np.random.randint(low = 20, high =100, size = [20,])
name = np.random.choice(['Divya', 'SSS', 'Ajay', 'Vinay', 'Satish'],20)
random = np.random.choice([10,11,13,12,14],20)

In [42]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random})

In [43]:
type(df)

pandas.core.frame.DataFrame

In [44]:
df.head(5)

temp    name  random
0    68  Satish      12
1    49   Vinay      14
2    33    Ajay      12
3    64   Divya      14
4    28   Vinay      11

In [45]:
df.tail()

temp    name  random
15    58     SSS      14
16    29   Vinay      11
17    29  Satish      14
18    97  Satish      13
19    48   Vinay      13

In [46]:
df.shape

(20, 3)

In [47]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [48]:
df.name

0     Satish
1      Vinay
2       Ajay
3      Divya
4      Vinay
5      Vinay
6        SSS
7      Vinay
8        SSS
9      Vinay
10     Vinay
11      Ajay
12      Ajay
13       SSS
14     Divya
15       SSS
16     Vinay
17    Satish
18    Satish
19     Vinay
Name: name, dtype: object

In [49]:
df['name']

0     Satish
1      Vinay
2       Ajay
3      Divya
4      Vinay
5      Vinay
6        SSS
7      Vinay
8        SSS
9      Vinay
10     Vinay
11      Ajay
12      Ajay
13       SSS
14     Divya
15       SSS
16     Vinay
17    Satish
18    Satish
19     Vinay
Name: name, dtype: object

In [50]:
df.info()
# row = Instances / data points/ data instances
# columns = Attributes or features

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int32
name      20 non-null object
random    20 non-null int32
dtypes: int32(2), object(1)
memory usage: 400.0+ bytes


In [51]:
df.describe()

temp     random
count  20.000000  20.000000
mean   51.550000  12.350000
std    21.431593   1.386969
min    21.000000  10.000000
25%    33.000000  11.750000
50%    49.000000  12.500000
75%    64.250000  13.250000
max    97.000000  14.000000

In [52]:
df['temp'].describe()

count    20.000000
mean     51.550000
std      21.431593
min      21.000000
25%      33.000000
50%      49.000000
75%      64.250000
max      97.000000
Name: temp, dtype: float64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int32
name      20 non-null object
random    20 non-null int32
dtypes: int32(2), object(1)
memory usage: 400.0+ bytes


In [54]:
df.values

array([[68, 'Satish', 12],
       [49, 'Vinay', 14],
       [33, 'Ajay', 12],
       [64, 'Divya', 14],
       [28, 'Vinay', 11],
       [33, 'Vinay', 14],
       [49, 'SSS', 13],
       [37, 'Vinay', 12],
       [66, 'SSS', 13],
       [21, 'Vinay', 12],
       [97, 'Vinay', 10],
       [56, 'Ajay', 10],
       [64, 'Ajay', 12],
       [40, 'SSS', 13],
       [65, 'Divya', 10],
       [58, 'SSS', 14],
       [29, 'Vinay', 11],
       [29, 'Satish', 14],
       [97, 'Satish', 13],
       [48, 'Vinay', 13]], dtype=object)

In [55]:
df

temp    name  random
0     68  Satish      12
1     49   Vinay      14
2     33    Ajay      12
3     64   Divya      14
4     28   Vinay      11
5     33   Vinay      14
6     49     SSS      13
7     37   Vinay      12
8     66     SSS      13
9     21   Vinay      12
10    97   Vinay      10
11    56    Ajay      10
12    64    Ajay      12
13    40     SSS      13
14    65   Divya      10
15    58     SSS      14
16    29   Vinay      11
17    29  Satish      14
18    97  Satish      13
19    48   Vinay      13

In [132]:
df.set_index('temp', inplace=True)

In [133]:
df

name  random
temp                    
93    Rajeshwari      10
57         Fenil      13
61       Akshaya      10
64       Akshaya      10
80    Rajeshwari      11
64       Akshaya      10
34       Hemanka      12
37    Rajeshwari      13
64    Rajeshwari      11
47        Shakti      11
56        Shakti      11
82       Akshaya      13
67        Shakti      14
36       Hemanka      11
47       Hemanka      11
65       Akshaya      11
41        Shakti      11
79       Akshaya      10
94        Shakti      10
29       Hemanka      14

In [134]:
df.sort_index(axis=0, ascending=True)

name  random
temp                    
29       Hemanka      14
34       Hemanka      12
36       Hemanka      11
37    Rajeshwari      13
41        Shakti      11
47       Hemanka      11
47        Shakti      11
56        Shakti      11
57         Fenil      13
61       Akshaya      10
64    Rajeshwari      11
64       Akshaya      10
64       Akshaya      10
65       Akshaya      11
67        Shakti      14
79       Akshaya      10
80    Rajeshwari      11
82       Akshaya      13
93    Rajeshwari      10
94        Shakti      10

In [59]:
df.sort_values(by='random', ascending = True)

name  random
temp                
65     Divya      10
56      Ajay      10
97     Vinay      10
29     Vinay      11
28     Vinay      11
68    Satish      12
64      Ajay      12
21     Vinay      12
33      Ajay      12
37     Vinay      12
66       SSS      13
97    Satish      13
49       SSS      13
40       SSS      13
48     Vinay      13
33     Vinay      14
64     Divya      14
58       SSS      14
49     Vinay      14
29    Satish      14

In [60]:
df.drop(['random'], axis=1)

name
temp        
68    Satish
49     Vinay
33      Ajay
64     Divya
28     Vinay
33     Vinay
49       SSS
37     Vinay
66       SSS
21     Vinay
97     Vinay
56      Ajay
64      Ajay
40       SSS
65     Divya
58       SSS
29     Vinay
29    Satish
97    Satish
48     Vinay

In [61]:
df

name  random
temp                
68    Satish      12
49     Vinay      14
33      Ajay      12
64     Divya      14
28     Vinay      11
33     Vinay      14
49       SSS      13
37     Vinay      12
66       SSS      13
21     Vinay      12
97     Vinay      10
56      Ajay      10
64      Ajay      12
40       SSS      13
65     Divya      10
58       SSS      14
29     Vinay      11
29    Satish      14
97    Satish      13
48     Vinay      13

In [62]:
df.iloc[1:11, :]

name  random
temp               
49    Vinay      14
33     Ajay      12
64    Divya      14
28    Vinay      11
33    Vinay      14
49      SSS      13
37    Vinay      12
66      SSS      13
21    Vinay      12
97    Vinay      10

In [63]:
df.iloc[10:16, :]

name  random
temp               
97    Vinay      10
56     Ajay      10
64     Ajay      12
40      SSS      13
65    Divya      10
58      SSS      14

In [64]:
df.iloc[:, 1]

temp
68    12
49    14
33    12
64    14
28    11
33    14
49    13
37    12
66    13
21    12
97    10
56    10
64    12
40    13
65    10
58    14
29    11
29    14
97    13
48    13
Name: random, dtype: int32

In [65]:
df.iloc[5:11, 0]

temp
33    Vinay
49      SSS
37    Vinay
66      SSS
21    Vinay
97    Vinay
Name: name, dtype: object

In [66]:
df.iloc[10:18, 1]

temp
97    10
56    10
64    12
40    13
65    10
58    14
29    11
29    14
Name: random, dtype: int32

In [67]:
df.iloc[5:10, 0:2]

name  random
temp               
33    Vinay      14
49      SSS      13
37    Vinay      12
66      SSS      13
21    Vinay      12

In [68]:
df.iloc[[9, 10], 1:2]

random
temp        
21        12
97        10

In [69]:
# iloc = index location
# loc = location - index or name

In [70]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random})

In [71]:
df.head()

temp    name  random
0    68  Satish      12
1    49   Vinay      14
2    33    Ajay      12
3    64   Divya      14
4    28   Vinay      11

In [72]:
df.loc[4,:]

temp         28
name      Vinay
random       11
Name: 4, dtype: object

In [73]:
df.loc[[1, 2, 5, 7, 12]]

temp   name  random
1     49  Vinay      14
2     33   Ajay      12
5     33  Vinay      14
7     37  Vinay      12
12    64   Ajay      12

In [74]:
df.loc[[7, 2, 15, 19, 4], ['name','random']]

name  random
7   Vinay      12
2    Ajay      12
15    SSS      14
19  Vinay      13
4   Vinay      11

In [75]:
df.loc[df.random > 12]

temp    name  random
1     49   Vinay      14
3     64   Divya      14
5     33   Vinay      14
6     49     SSS      13
8     66     SSS      13
13    40     SSS      13
15    58     SSS      14
17    29  Satish      14
18    97  Satish      13
19    48   Vinay      13

In [76]:
df.loc[(df.random > 13) | (df.random == 10),:]

temp    name  random
1     49   Vinay      14
3     64   Divya      14
5     33   Vinay      14
10    97   Vinay      10
11    56    Ajay      10
14    65   Divya      10
15    58     SSS      14
17    29  Satish      14

In [136]:
# Merging & concat
d1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['col1', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [137]:
d1

col1  number
0    a       1
1    b       2

In [138]:
d2

letter  number animal
0      c       3   lion
1      d       4  tiger

In [140]:
pd.concat([d1,d2], axis =0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
0   lion  NaN      c       3
1  tiger  NaN      d       4

In [81]:
pd.concat([d1,d2], axis =0, ignore_index=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
2   lion  NaN      c       3
3  tiger  NaN      d       4

In [82]:
pd.concat([d1,d2], axis = 1)

col1  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [141]:
d1 = pd.DataFrame({
    "city" : ["lucknow","kanpur","agra","delhi"],
    "temperature" : [32,45,30,40]
})

In [142]:
d1

city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [143]:
d2 = pd.DataFrame({
    "city" : ["delhi","lucknow","kanpur"],
    "humidity" : [68,65,75]
})

In [144]:
d2

city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75

In [145]:
df = pd.merge(d1,d2, on='city')

In [146]:
df

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68

In [89]:
pd.merge(d1,d2, on=['city'], how ='outer')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [90]:
# pd.merge(d1, d2, on =['city'], how='left')

In [91]:
# dataset from https://github.com/codebasics/py/blob/master/pandas/6_handling_missing_data_replace/weather_data.csv

# CSV - Comma separated Values

In [92]:
df1 = pd.read_csv("weather_data.csv")

In [93]:
df1 

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [94]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
day            6 non-null object
temperature    6 non-null int64
windspeed      6 non-null int64
event          6 non-null object
dtypes: int64(2), object(2)
memory usage: 272.0+ bytes


In [95]:
df1.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [96]:
df1.shape

(6, 4)

In [97]:
"""
csv
xl
matlab
hd5y
json
"""

'\ncsv\nxl\nmatlab\nhd5y\njson\n'

In [98]:
!pip3 install openpyxl
df1.to_excel('df_xl.xlsx', sheet_name = 'weather_data', index=False)

  Using cached https://files.pythonhosted.org/packages/6f/af/88ff9eef0b8f665aee1111ac6cede5ad12190c5bd726242bd2b26fc21b32/openpyxl-3.0.0.tar.gz
  Using cached https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz


Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "c:\program files\pytho

In [99]:
!pip3 install xlrd
df2 = pd.read_excel('df_xl.xlsx')

  Using cached https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl


Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "c:\program files\python36\lib\site-pa

In [100]:
df2

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [101]:
df2.to_csv('file.csv')

In [102]:
df2.to_csv('file_noindex.csv', index = False)

In [147]:
df_group = df2.groupby("event")

In [148]:
df_group

In [105]:
for entries in df_group:
    print(entries)

('Rain',         day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain)
('Snow',         day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow)
('Sunny',         day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
5  1/6/2017           31          2  Sunny)


In [106]:
df_group.get_group('Rain')

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [107]:
df_group.describe()

temperature                                               windspeed  \
            count  mean       std   min   25%   50%   75%   max     count   
event                                                                       
Rain          2.0  32.0  0.000000  32.0  32.0  32.0  32.0  32.0       2.0   
Snow          2.0  26.0  2.828427  24.0  25.0  26.0  27.0  28.0       2.0   
Sunny         2.0  33.0  2.828427  31.0  32.0  33.0  34.0  35.0       2.0   

                                                 
      mean       std  min   25%  50%   75%  max  
event                                            
Rain   5.0  1.414214  4.0  4.50  5.0  5.50  6.0  
Snow   4.5  3.535534  2.0  3.25  4.5  5.75  7.0  
Sunny  4.5  3.535534  2.0  3.25  4.5  5.75  7.0

In [108]:
def hot_temp(x):
    return x > 30

In [109]:
df2['hot_temp'] = df2['temperature'].apply(hot_temp)

In [110]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True