# Create Pandas Series

In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
a = pd.Series([1,2,3,4,5])

In [4]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(a)

pandas.core.series.Series

In [6]:
a[2]

3

In [7]:
a = pd.Series(['a','b','c'])

In [8]:
a

0    a
1    b
2    c
dtype: object

In [9]:
a = pd.date_range(start = '01-01-2019', end = '24-10-2019')

In [10]:
a

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-10-15', '2019-10-16', '2019-10-17', '2019-10-18',
               '2019-10-19', '2019-10-20', '2019-10-21', '2019-10-22',
               '2019-10-23', '2019-10-24'],
              dtype='datetime64[ns]', length=297, freq='D')

In [11]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

# Pandas dataframe

In [12]:
name = ['Shakti', 'Hemanka', 'Rajeshwari', 'Akshaya', 'Fenil']

In [13]:
domain = ['NLP', 'Reinforcement Learning', 'Computer Vision', 'Analytrics', 'Automation']

In [14]:
experience = [2, 3, 4, 5, 6]

In [15]:
dct = {'Name': name, 'Domain': domain, 'Experience': experience}

In [16]:
data = pd.DataFrame(dct)

In [17]:
data

Name                  Domain  Experience
0      Shakti                     NLP           2
1     Hemanka  Reinforcement Learning           3
2  Rajeshwari         Computer Vision           4
3     Akshaya              Analytrics           5
4       Fenil              Automation           6

In [18]:
zipped = list(zip(name, domain, experience))

In [19]:
zipped

[('Shakti', 'NLP', 2),
 ('Hemanka', 'Reinforcement Learning', 3),
 ('Rajeshwari', 'Computer Vision', 4),
 ('Akshaya', 'Analytrics', 5),
 ('Fenil', 'Automation', 6)]

In [ ]:
data = {'Name':name,
       'Domain':domain,
       'Experience':experience}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

In [20]:
import numpy as np

In [21]:
np.random.randint(low=10, high=100, size=10)

array([73, 32, 94, 62, 61, 76, 24, 19, 99, 51])

In [22]:
np.random.choice([1, 2, 3, 4, 5, 6], 5)

array([6, 3, 6, 3, 5])

In [23]:
temp = np.random.randint(low = 20, high =100, size = [20,])
name = np.random.choice(['Shakti', 'Hemanka', 'Rajeshwari', 'Akshaya', 'Fenil'], 20)
random = np.random.choice([10,11,13,12,14], 20)

In [24]:
temp

array([84, 75, 36, 20, 79, 85, 31, 91, 62, 76, 33, 80, 81, 50, 68, 40, 63,
       50, 49, 22])

In [25]:
name

array(['Rajeshwari', 'Hemanka', 'Hemanka', 'Shakti', 'Fenil', 'Akshaya',
       'Shakti', 'Akshaya', 'Rajeshwari', 'Akshaya', 'Shakti', 'Hemanka',
       'Hemanka', 'Hemanka', 'Akshaya', 'Rajeshwari', 'Rajeshwari',
       'Rajeshwari', 'Shakti', 'Shakti'], dtype='<U10')

In [26]:
random

array([10, 12, 14, 13, 12, 11, 14, 13, 12, 12, 14, 12, 10, 11, 13, 12, 10,
       13, 14, 12])

In [27]:
a = list(zip(temp, name, random))

In [28]:
a

[(84, 'Rajeshwari', 10),
 (75, 'Hemanka', 12),
 (36, 'Hemanka', 14),
 (20, 'Shakti', 13),
 (79, 'Fenil', 12),
 (85, 'Akshaya', 11),
 (31, 'Shakti', 14),
 (91, 'Akshaya', 13),
 (62, 'Rajeshwari', 12),
 (76, 'Akshaya', 12),
 (33, 'Shakti', 14),
 (80, 'Hemanka', 12),
 (81, 'Hemanka', 10),
 (50, 'Hemanka', 11),
 (68, 'Akshaya', 13),
 (40, 'Rajeshwari', 12),
 (63, 'Rajeshwari', 10),
 (50, 'Rajeshwari', 13),
 (49, 'Shakti', 14),
 (22, 'Shakti', 12)]

In [29]:
df = pd.DataFrame(data = a, columns=['temp','name','random'])

In [30]:
df

temp        name  random
0     84  Rajeshwari      10
1     75     Hemanka      12
2     36     Hemanka      14
3     20      Shakti      13
4     79       Fenil      12
5     85     Akshaya      11
6     31      Shakti      14
7     91     Akshaya      13
8     62  Rajeshwari      12
9     76     Akshaya      12
10    33      Shakti      14
11    80     Hemanka      12
12    81     Hemanka      10
13    50     Hemanka      11
14    68     Akshaya      13
15    40  Rajeshwari      12
16    63  Rajeshwari      10
17    50  Rajeshwari      13
18    49      Shakti      14
19    22      Shakti      12

In [35]:
df.head()

temp        name  random
0    84  Rajeshwari      10
1    75     Hemanka      12
2    36     Hemanka      14
3    20      Shakti      13
4    79       Fenil      12

In [38]:
df.tail(3)

temp        name  random
17    50  Rajeshwari      13
18    49      Shakti      14
19    22      Shakti      12

In [39]:
type(df)

pandas.core.frame.DataFrame

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int64
name      20 non-null object
random    20 non-null int64
dtypes: int64(2), object(1)
memory usage: 560.0+ bytes


In [41]:
df.shape

(20, 3)

In [42]:
df.describe()

temp     random
count  20.000000  20.000000
mean   58.750000  12.200000
std    22.713027   1.321881
min    20.000000  10.000000
25%    39.000000  11.750000
50%    62.500000  12.000000
75%    79.250000  13.000000
max    91.000000  14.000000

In [44]:
df['name']

0     Rajeshwari
1        Hemanka
2        Hemanka
3         Shakti
4          Fenil
5        Akshaya
6         Shakti
7        Akshaya
8     Rajeshwari
9        Akshaya
10        Shakti
11       Hemanka
12       Hemanka
13       Hemanka
14       Akshaya
15    Rajeshwari
16    Rajeshwari
17    Rajeshwari
18        Shakti
19        Shakti
Name: name, dtype: object

In [69]:
temp = np.random.randint(low = 20, high =100, size = [20,])
name = np.random.choice(['Divya', 'SSS', 'Ajay', 'Vinay', 'Satish'],20)
random = np.random.choice([10,11,13,12,14],20)

In [70]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random})

In [47]:
type(df)

pandas.core.frame.DataFrame

In [71]:
df.head(5)

temp   name  random
0    37   Ajay      12
1    28  Divya      11
2    87    SSS      14
3    47   Ajay      13
4    96    SSS      12

In [49]:
df.tail()

temp    name  random
15    89  Satish      13
16    69   Divya      10
17    47   Divya      10
18    95   Divya      14
19    30  Satish      11

In [50]:
df.shape

(20, 3)

In [51]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [52]:
df.name

0      Vinay
1        SSS
2     Satish
3      Vinay
4     Satish
5      Vinay
6       Ajay
7     Satish
8       Ajay
9       Ajay
10     Divya
11       SSS
12       SSS
13     Vinay
14       SSS
15    Satish
16     Divya
17     Divya
18     Divya
19    Satish
Name: name, dtype: object

In [53]:
df['name']

0      Vinay
1        SSS
2     Satish
3      Vinay
4     Satish
5      Vinay
6       Ajay
7     Satish
8       Ajay
9       Ajay
10     Divya
11       SSS
12       SSS
13     Vinay
14       SSS
15    Satish
16     Divya
17     Divya
18     Divya
19    Satish
Name: name, dtype: object

In [54]:
df.info()
# row = Instances
# columns = Attributes or features

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int32
name      20 non-null object
random    20 non-null int32
dtypes: int32(2), object(1)
memory usage: 400.0+ bytes


In [55]:
df.describe()

temp     random
count  20.000000  20.000000
mean   61.850000  11.600000
std    20.881306   1.602629
min    30.000000  10.000000
25%    47.000000  10.000000
50%    58.500000  11.000000
75%    74.250000  13.000000
max    98.000000  14.000000

In [56]:
df['temp'].describe()

count    20.000000
mean     61.850000
std      20.881306
min      30.000000
25%      47.000000
50%      58.500000
75%      74.250000
max      98.000000
Name: temp, dtype: float64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int32
name      20 non-null object
random    20 non-null int32
dtypes: int32(2), object(1)
memory usage: 400.0+ bytes


In [58]:
df.values

array([[70, 'Vinay', 13],
       [89, 'SSS', 13],
       [47, 'Satish', 12],
       [55, 'Vinay', 14],
       [62, 'Satish', 11],
       [58, 'Vinay', 10],
       [63, 'Ajay', 10],
       [32, 'Satish', 10],
       [55, 'Ajay', 14],
       [41, 'Ajay', 13],
       [56, 'Divya', 10],
       [98, 'SSS', 13],
       [87, 'SSS', 10],
       [35, 'Vinay', 11],
       [59, 'SSS', 10],
       [89, 'Satish', 13],
       [69, 'Divya', 10],
       [47, 'Divya', 10],
       [95, 'Divya', 14],
       [30, 'Satish', 11]], dtype=object)

In [59]:
df

temp    name  random
0     70   Vinay      13
1     89     SSS      13
2     47  Satish      12
3     55   Vinay      14
4     62  Satish      11
5     58   Vinay      10
6     63    Ajay      10
7     32  Satish      10
8     55    Ajay      14
9     41    Ajay      13
10    56   Divya      10
11    98     SSS      13
12    87     SSS      10
13    35   Vinay      11
14    59     SSS      10
15    89  Satish      13
16    69   Divya      10
17    47   Divya      10
18    95   Divya      14
19    30  Satish      11

In [60]:
df.set_index('temp', inplace = True)

In [61]:
df

name  random
temp                
70     Vinay      13
89       SSS      13
47    Satish      12
55     Vinay      14
62    Satish      11
58     Vinay      10
63      Ajay      10
32    Satish      10
55      Ajay      14
41      Ajay      13
56     Divya      10
98       SSS      13
87       SSS      10
35     Vinay      11
59       SSS      10
89    Satish      13
69     Divya      10
47     Divya      10
95     Divya      14
30    Satish      11

In [62]:
df.sort_index(axis=0, ascending=False)

name  random
temp                
98       SSS      13
95     Divya      14
89    Satish      13
89       SSS      13
87       SSS      10
70     Vinay      13
69     Divya      10
63      Ajay      10
62    Satish      11
59       SSS      10
58     Vinay      10
56     Divya      10
55      Ajay      14
55     Vinay      14
47     Divya      10
47    Satish      12
41      Ajay      13
35     Vinay      11
32    Satish      10
30    Satish      11

In [63]:
df.sort_values(by='random', ascending = True)

name  random
temp                
47     Divya      10
69     Divya      10
58     Vinay      10
63      Ajay      10
32    Satish      10
59       SSS      10
56     Divya      10
87       SSS      10
30    Satish      11
62    Satish      11
35     Vinay      11
47    Satish      12
89    Satish      13
70     Vinay      13
89       SSS      13
98       SSS      13
41      Ajay      13
95     Divya      14
55      Ajay      14
55     Vinay      14

In [64]:
df.drop(['random'], axis=1)

name
temp        
70     Vinay
89       SSS
47    Satish
55     Vinay
62    Satish
58     Vinay
63      Ajay
32    Satish
55      Ajay
41      Ajay
56     Divya
98       SSS
87       SSS
35     Vinay
59       SSS
89    Satish
69     Divya
47     Divya
95     Divya
30    Satish

In [72]:
df

temp   name  random
0     37   Ajay      12
1     28  Divya      11
2     87    SSS      14
3     47   Ajay      13
4     96    SSS      12
5     96   Ajay      13
6     56   Ajay      13
7     22    SSS      10
8     93   Ajay      13
9     48  Vinay      11
10    49   Ajay      11
11    89  Vinay      14
12    97    SSS      10
13    32  Divya      12
14    69   Ajay      14
15    56  Vinay      14
16    27    SSS      14
17    93    SSS      11
18    83  Vinay      11
19    61  Divya      10

In [73]:
df.iloc[1:11, :]

temp   name  random
1     28  Divya      11
2     87    SSS      14
3     47   Ajay      13
4     96    SSS      12
5     96   Ajay      13
6     56   Ajay      13
7     22    SSS      10
8     93   Ajay      13
9     48  Vinay      11
10    49   Ajay      11

In [74]:
df.iloc[10:16, :]

temp   name  random
10    49   Ajay      11
11    89  Vinay      14
12    97    SSS      10
13    32  Divya      12
14    69   Ajay      14
15    56  Vinay      14

In [76]:
df.iloc[:, 1]

0      Ajay
1     Divya
2       SSS
3      Ajay
4       SSS
5      Ajay
6      Ajay
7       SSS
8      Ajay
9     Vinay
10     Ajay
11    Vinay
12      SSS
13    Divya
14     Ajay
15    Vinay
16      SSS
17      SSS
18    Vinay
19    Divya
Name: name, dtype: object

In [77]:
df.iloc[5:11, 0]

5     96
6     56
7     22
8     93
9     48
10    49
Name: temp, dtype: int32

In [78]:
df.iloc[10:18, 1]

10     Ajay
11    Vinay
12      SSS
13    Divya
14     Ajay
15    Vinay
16      SSS
17      SSS
Name: name, dtype: object

In [79]:
df.iloc[5:10, 0:2]

temp   name
5    96   Ajay
6    56   Ajay
7    22    SSS
8    93   Ajay
9    48  Vinay

In [80]:
df.iloc[[9, 10], 1:2]

name
9   Vinay
10   Ajay

In [ ]:
# iloc = index location
# loc = location - index or name

In [81]:
df.head()

temp   name  random
0    37   Ajay      12
1    28  Divya      11
2    87    SSS      14
3    47   Ajay      13
4    96    SSS      12

In [82]:
df.loc[4,:]

temp       96
name      SSS
random     12
Name: 4, dtype: object

In [83]:
df.loc[[1, 2, 5, 7, 12]]

temp   name  random
1     28  Divya      11
2     87    SSS      14
5     96   Ajay      13
7     22    SSS      10
12    97    SSS      10

In [84]:
df.loc[[7, 2, 15, 19, 4], ['name','random']]

name  random
7     SSS      10
2     SSS      14
15  Vinay      14
19  Divya      10
4     SSS      12

In [85]:
df.loc[df.random > 12]

temp   name  random
2     87    SSS      14
3     47   Ajay      13
5     96   Ajay      13
6     56   Ajay      13
8     93   Ajay      13
11    89  Vinay      14
14    69   Ajay      14
15    56  Vinay      14
16    27    SSS      14

In [86]:
df.loc[(df.random > 13) | (df.random == 10),:]

temp   name  random
2     87    SSS      14
7     22    SSS      10
11    89  Vinay      14
12    97    SSS      10
14    69   Ajay      14
15    56  Vinay      14
16    27    SSS      14
19    61  Divya      10

In [87]:
# Merging & concat
d1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['col1', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [88]:
d1

col1  number
0    a       1
1    b       2

In [89]:
d2

letter  number animal
0      c       3   lion
1      d       4  tiger

In [90]:
pd.concat([d1,d2], axis =0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
0   lion  NaN      c       3
1  tiger  NaN      d       4

In [91]:
pd.concat([d1,d2], axis =0, ignore_index=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
2   lion  NaN      c       3
3  tiger  NaN      d       4

In [92]:
pd.concat([d1,d2], axis = 1)

col1  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [93]:
d1 = pd.DataFrame({
    "city" : ["lucknow","kanpur","agra","delhi"],
    "temperature" : [32,45,30,40]
})

In [94]:
d1

city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [95]:
d2 = pd.DataFrame({
    "city" : ["delhi","lucknow","kanpur"],
    "humidity" : [68,65,75]
})

In [96]:
d2

city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75

In [97]:
df = pd.merge(d1,d2, on='city')

In [98]:
df

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68

In [99]:
pd.merge(d1,d2, on=['city'], how ='outer')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [ ]:
# pd.merge(d1, d2, on =['city'], how='left')

In [ ]:
# dataset from https://github.com/codebasics/py/blob/master/pandas/6_handling_missing_data_replace/weather_data.csv

# CSV - Comma separated Values

In [100]:
df1 = pd.read_csv("weather_data.csv")

In [101]:
df1 

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [102]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
day            6 non-null object
temperature    6 non-null int64
windspeed      6 non-null int64
event          6 non-null object
dtypes: int64(2), object(2)
memory usage: 272.0+ bytes


In [103]:
df1.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [104]:
df1.shape

(6, 4)

In [ ]:
"""
csv
xl
matlab
hd5y
json
"""

In [105]:
!pip3 install openpyxl
df1.to_excel('df_xl.xlsx', sheet_name = 'weather_data', index=False)

Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "c:\program files\pytho

In [106]:
!pip3 install xlrd
df2 = pd.read_excel('df_xl.xlsx')

Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files\python36\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "c:\program files\python36\lib\site-pa

In [107]:
df2

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [108]:
df2.to_csv('file.csv')

In [109]:
df2.to_csv('file_noindex.csv', index = False)

In [110]:
df_group = df2.groupby("event")

In [111]:
df_group

In [112]:
for entries in df_group:
    print(entries)

('Rain',         day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain)
('Snow',         day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow)
('Sunny',         day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
5  1/6/2017           31          2  Sunny)


In [113]:
df_group.get_group('Rain')

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [114]:
df_group.describe()

temperature                                               windspeed  \
            count  mean       std   min   25%   50%   75%   max     count   
event                                                                       
Rain          2.0  32.0  0.000000  32.0  32.0  32.0  32.0  32.0       2.0   
Snow          2.0  26.0  2.828427  24.0  25.0  26.0  27.0  28.0       2.0   
Sunny         2.0  33.0  2.828427  31.0  32.0  33.0  34.0  35.0       2.0   

                                                 
      mean       std  min   25%  50%   75%  max  
event                                            
Rain   5.0  1.414214  4.0  4.50  5.0  5.50  6.0  
Snow   4.5  3.535534  2.0  3.25  4.5  5.75  7.0  
Sunny  4.5  3.535534  2.0  3.25  4.5  5.75  7.0

In [115]:
def hot_temp(x):
    return x > 30

In [116]:
df2['hot_temp'] = df2['temperature'].apply(hot_temp)

In [117]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [118]:
df2['hot_temp'] = df2['temperature'].apply(lambda x: x > 30)

In [119]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True